export const SITE_NAME = "VOXEL";

export const seedGames = [
  {
    id: "game_repo",
    title: "R.E.P.O.",
    description:
      "An online co-op horror game with up to 6 players. Locate valuable, fully physics-based objects and handle them with care as you retrieve and extract to satisfy your creator's desires. Every run is loud, messy, and dangerously funny.",
    developer: "Semiwork",
    releaseDate: "2025-02-26",
    coverImage: "/images/browse-game.png",
    bannerImage: "/images/browse-game.png",
    genres: ["Horror", "Action", "Adventure"],
    tags: ["Co-op", "Multiplayer", "Singleplayer", "Early Access"],
    platforms: ["PC"],
    averageRating: 4.8,
    reviewCount: 128,
  },
  {
    id: "game_nightfall",
    title: "Nightfall Protocol",
    description:
      "A tactical night-ops shooter where information is scarce and every mistake is loud. Squad up for infiltration runs across procedurally scrambled city blocks, wire cameras, clear choke points, and extract before dawn breaks the stealth fantasy.",
    developer: "Black Iris Studio",
    releaseDate: "2024-11-12",
    coverImage: "/images/review-cover.png",
    bannerImage: "/images/browse-game.png",
    genres: ["Action", "Strategy"],
    tags: ["Singleplayer", "Story-rich", "Co-op", "Multiplayer"],
    platforms: ["PC", "PLAYSTATION", "XBOX"],
    averageRating: 4.5,
    reviewCount: 86,
  },
  {
    id: "game_ember",
    title: "Ember Circuit",
    description:
      "Neon racing through collapsing city circuits with high-risk boost routes. Draft behind rivals, overcharge your frame, and thread shortcuts that only stay open for a few frantic seconds before the track burns out behind you.",
    developer: "Voltage Frame",
    releaseDate: "2024-09-03",
    coverImage: "/images/browse-game.png",
    bannerImage: "/images/browse-game.png",
    genres: ["Sports", "Action", "Simulation"],
    tags: ["Competitive", "Multiplayer", "Singleplayer"],
    platforms: ["PC", "PLAYSTATION", "XBOX", "NINTENDO"],
    averageRating: 4.2,
    reviewCount: 54,
  },
  {
    id: "game_hollow",
    title: "Hollow Signal",
    description:
      "A slow-burn survival mystery about transmission, isolation, and what answers after dark. Tune abandoned relays, decode fragmented broadcasts, and decide how much truth your crew can survive when the signal finally talks back.",
    developer: "Quiet Frequency",
    releaseDate: "2025-01-17",
    coverImage: "/images/review-cover.png",
    bannerImage: "/images/review-cover.png",
    genres: ["Adventure", "Horror", "Puzzle"],
    tags: ["Singleplayer", "Story-rich", "Indie"],
    platforms: ["PC", "PLAYSTATION"],
    averageRating: 4.9,
    reviewCount: 203,
  },
  {
    id: "game_ashreach",
    title: "Ashreach",
    description:
      "Build outposts across a scorched frontier while rival clans contest every scrap of land. Harvest salvage, fortify routes, and decide whether to trade, raid, or hold the line when the ash storms roll in.",
    developer: "Emberline Collective",
    releaseDate: "2024-06-21",
    coverImage: "/images/browse-game.png",
    bannerImage: "/images/browse-game.png",
    genres: ["Strategy", "Simulation", "Action"],
    tags: ["Multiplayer", "Co-op", "Early Access"],
    platforms: ["PC", "XBOX"],
    averageRating: 4.1,
    reviewCount: 67,
  },
  {
    id: "game_drift",
    title: "Drift Syntax",
    description:
      "An indie puzzle-platformer about rewiring gravity and rewriting your last mistake. Each chamber is a logic trap dressed as architecture — shift panels, loop momentum, and chase a perfect run through rooms that remember every failure.",
    developer: "Nullroom Games",
    releaseDate: "2025-03-04",
    coverImage: "/images/review-cover.png",
    bannerImage: "/images/review-cover.png",
    genres: ["Puzzle", "Adventure", "Action"],
    tags: ["Singleplayer", "Indie", "Story-rich"],
    platforms: ["PC", "NINTENDO"],
    averageRating: 4.6,
    reviewCount: 41,
  },
  {
    id: "game_iron_meridian",
    title: "Iron Meridian",
    description:
      "A squad-based RPG set on a dying rail-world where factions fight over the last working lines. Customize loadouts, negotiate fragile alliances, and choose which stations survive when the meridian finally snaps.",
    developer: "Northspur Interactive",
    releaseDate: "2024-10-08",
    coverImage: "/images/browse-game.png",
    bannerImage: "/images/review-cover.png",
    genres: ["RPG", "Strategy", "Adventure"],
    tags: ["Singleplayer", "Story-rich", "Co-op"],
    platforms: ["PC", "PLAYSTATION", "XBOX"],
    averageRating: 4.4,
    reviewCount: 92,
  },
  {
    id: "game_coral_deep",
    title: "Coral Deep",
    description:
      "Descend through flooded arcologies to restore power, map lost habitats, and keep your submersible intact. Calm exploration punctuates tense salvage dives where oxygen, pressure, and what lives in the dark all run out at once.",
    developer: "Tideglass Studio",
    releaseDate: "2025-01-30",
    coverImage: "/images/review-cover.png",
    bannerImage: "/images/browse-game.png",
    genres: ["Adventure", "Simulation", "Puzzle"],
    tags: ["Singleplayer", "Indie", "Story-rich"],
    platforms: ["PC", "PLAYSTATION"],
    averageRating: 4.7,
    reviewCount: 58,
  },
  {
    id: "game_static_bloom",
    title: "Static Bloom",
    description:
      "A horror-action roguelite where corrupted broadcasts rewrite the battlefield mid-fight. Clear signal towers, survive wave mutations, and unlock gear that turns the static from enemy to weapon.",
    developer: "Latchpoint Audio",
    releaseDate: "2024-12-11",
    coverImage: "/images/browse-game.png",
    bannerImage: "/images/browse-game.png",
    genres: ["Horror", "Action", "Adventure"],
    tags: ["Singleplayer", "Early Access", "Competitive"],
    platforms: ["PC"],
    averageRating: 4.3,
    reviewCount: 73,
  },
  {
    id: "game_crownfall",
    title: "Crownfall",
    description:
      "A grand strategy campaign about succession, siegecraft, and starving courts. Manage provinces, broker marriages, and march armies across a map that remembers every broken treaty.",
    developer: "Red Ledger Games",
    releaseDate: "2024-04-15",
    coverImage: "/images/review-cover.png",
    bannerImage: "/images/review-cover.png",
    genres: ["Strategy", "Simulation"],
    tags: ["Singleplayer", "Multiplayer", "Story-rich"],
    platforms: ["PC", "PLAYSTATION", "XBOX", "NINTENDO"],
    averageRating: 4.0,
    reviewCount: 115,
  },
] as const;

export const seedReviews = [
  {
    id: "review_featured",
    title: "A MASTERCLASS IN TENSION",
    content:
      "From the opening hours this game refuses to let you breathe. Combat is spiteful in the best way, exploration is rewarding, and the story sticks the landing without sanding off the edges.",
    rating: 5,
    authorName: "@pixelbruise",
    displayName: "daylight",
    userName: "danaln",
    coverImage: null,
    featured: true,
    gameId: "game_hollow",
    status: "Playing",
  },
  {
    id: "review_1",
    title: "THIS IS BADASS!",
    content:
      "We play the bugs, endure the grinds, and celebrate the masterpieces so you don’t waste your time or money. We play the bugs, endure the grinds, and celebrate the masterpieces so you don’t waste your bug bug celebrate the masterpieces so you don’t waste your bug bug celebrate the your bug bug I LOOOOOOOVE I LOVE I LOVE I LOVE",
    rating: 5,
    authorName: "@danaln",
    displayName: "daylight",
    userName: "danaln",
    coverImage: "/images/review-cover.png",
    featured: false,
    gameId: "game_repo",
    status: "Playing",
  },
  {
    id: "review_2",
    title: "WORTH EVERY LATE NIGHT",
    content:
      "The loop clicks by hour three and never lets go. Builds feel expressive, bosses feel fair, and the soundtrack carries every long session without getting stale.",
    rating: 5,
    authorName: "@danaln",
    displayName: "daylight",
    userName: "danaln",
    coverImage: "/images/review-cover.png",
    featured: false,
    gameId: "game_nightfall",
    status: "Finished",
  },
  {
    id: "review_3",
    title: "ROUGH EDGES, REAL HEART",
    content:
      "It stumbles in the midgame, but the characters and systems keep pulling you back. If you can push through the rough patches, there is a special campaign waiting underneath.",
    rating: 4,
    authorName: "@danaln",
    displayName: "daylight",
    userName: "danaln",
    coverImage: "/images/review-cover.png",
    featured: false,
    gameId: "game_ember",
    status: "Dropped",
  },
  {
    id: "review_4",
    title: "CAN'T STOP RECOMMENDING THIS",
    content:
      "Atmosphere for days, encounters that stay scary, and a pace that respects your time. Not perfect, but it is one of the clearest must-plays on the board right now.",
    rating: 5,
    authorName: "@danaln",
    displayName: "daylight",
    userName: "danaln",
    coverImage: "/images/review-cover.png",
    featured: false,
    gameId: "game_hollow",
    status: "Finished",
  },
  {
    id: "review_5",
    title: "FRONTIER WARFARE DONE RIGHT",
    content:
      "Base building clicks fast and raids feel earned. The ash storms are chaos in the best way — you will lose outposts, rebuild, and immediately want another run.",
    rating: 4,
    authorName: "@pixelbruise",
    displayName: "Pixel Bruise",
    userName: "pixelbruise",
    coverImage: "/images/review-cover.png",
    featured: false,
    gameId: "game_ashreach",
    status: "Playing",
  },
  {
    id: "review_6",
    title: "BRAIN-BENDING IN THE BEST WAY",
    content:
      "Every room is a tiny eureka machine. Short, sharp levels with just enough story to make the final chamber hit harder than it should.",
    rating: 5,
    authorName: "@danaln",
    displayName: "daylight",
    userName: "danaln",
    coverImage: "/images/review-cover.png",
    featured: false,
    gameId: "game_drift",
    status: "Finished",
  },
  {
    id: "review_7",
    title: "DEEP, SLOW, UNFORGETTABLE",
    content:
      "Coral Deep rewards patience. The atmosphere is incredible and the pressure mechanics keep every dive tense without feeling unfair.",
    rating: 5,
    authorName: "@pixelbruise",
    displayName: "Pixel Bruise",
    userName: "pixelbruise",
    coverImage: null,
    featured: false,
    gameId: "game_coral_deep",
    status: "Finished",
  },
  {
    id: "review_8",
    title: "MAP PAINTING ADDICTION",
    content:
      "Crownfall is dense but fair. One more turn syndrome is real — just one more treaty, one more siege, one more province.",
    rating: 4,
    authorName: "@danaln",
    displayName: "daylight",
    userName: "danaln",
    coverImage: "/images/review-cover.png",
    featured: false,
    gameId: "game_crownfall",
    status: "Playing",
  },
] as const;

export const seedHeroSecondaryReview = {
  id: "review_hero_secondary",
  title: "ONE MORE RUN ENERGY",
  content:
    "Short sessions turn into all-nighters. The risk-reward loop is addictive and the co-op screams are worth it.",
  rating: 4,
  authorName: "@danaln",
  displayName: "daylight",
  userName: "danaln",
  coverImage: null,
  featured: false,
  status: "Playing",
  likeCount: 0,
  likedByMe: false,
} as const;

export const seedUsers = [
  {
    id: "danaln",
    email: "dana.alania@gmail.com",
    username: "danaln",
    displayName: "daylight",
    profileImg: null,
    bio: "WOWOWOWOW BIO im a gaymer girl in a gaymer world life is plastic its fantastic",
    reviews: ["review_1"],
    followers: 67,
    following: 69,
    likedGameIds: ["game_repo", "game_nightfall"] as string[],
    reviewIds: ["review_1", "review_2", "review_3"] as string[],
  },
];
